language: ruby
# only run CI-builds on master branch
branches:
  only:
  - dev
rvm:
  - 2.7
# set execution permission on our build script
before_install:
  - gem install bundler
before_script:
  - chmod +x ./script/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false